CompleteDataset <- read.table("./download/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE) 
Data <-subset(CompleteDataset, Date =="1/2/2007" | Date =="2/2/2007")
DT <- strptime(paste(Data$Date, Data$Time, sep=" "),"%d/%m/%Y %H:%M:%S")  
Data$Sub_metering_1 <- as.numeric(Data$Sub_metering_1)
Data$Sub_metering_2 <- as.numeric(Data$Sub_metering_2)
Data$Sub_metering_3 <- as.numeric(Data$Sub_metering_3)
png("plot3.png", width=480, height=480)
plot(DT, Data$Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(DT,Data$Sub_metering_2, type="l", xlab="", ylab="", col="red")
lines(DT,Data$Sub_metering_3, type="l", xlab="", ylab="", col="blue")
legend(x="topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), 
      col=c("black", "red", "blue"), lty=1)
dev.off()